### ISSUE TITLE
Multiple WebCommander Instances or restrict access to scripts

### ISSUE THREAD

**Issue by aschi75** [vmware/webcommander#51] opened 2015-05-21 04:50 UTC
Hi 
I have multiple WebCommander Instances because not all Users are allowed to execute everything.
To be able to restrict access I have for each instance a Website where I can select with IIS Authorization Rules which users are allowed to access the Startpage and the scripts beneath.
But this isn't a good solution because I have to maintain a lot during an upgrade and other things.

An easier way would be if I could place the scripts in subfolders under \powershell like
\powershell\department1\..
\powershell\department2\..
But In this case I'm NOT able to restrict the access to the different Scripts in the powershell subfolders. All these people who are allowed to access the Startpage can execute all scripts. It doesn’t matter how I set the ntfs permission on the Folders under \powershell because the scripts itself are executed as Administsrator.

It should be possible that I can restrict the scripts in subfolder of powershell to specific Groups.
Not Permitted Scripts should not be listed on the Startpage of WebCommander.
A simple solution would be appreciated.

Best Regards,
Roger Aschwanden
Accarda AG

**Comment by 9whirls** [comment] 2015-05-21 07:11
![applicationpoolidentity](https://cloud.githubusercontent.com/assets/7997931/7743205/570361e8-ff4d-11e4-9605-8f000570ab2a.png)

Hi Roger, when you use Windows Authentication, please make sure the process indentity is set to ApplicationPoolIdentity as showed in the screen shot.

You may find more detailed explanation at http://www.iis.net/learn/get-started/planning-for-security/secure-content-in-iis-through-file-system-acls.

Let me know if you need further assistance.

**Comment by aschi75** [comment] 2015-05-21 08:08
Hi Jerry
The Identity was already set as shown in the Printscreen to ApplicationPoolIdentity. But even if the User doesn't have any ACL Permission on the Filesystem he is able to see all scripts and execute it. Maybe it should work this way and something else is misconfigured. I read the article you posted but don't understand how IIS should make the difference. It's still one "virtual identity". Where do I have to configure the permission to restrict the access to different Users and Groups? I set "fastcgi.impersonate = 1" in the php.ini but it didn't make any difference.

**Comment by 9whirls** [comment] 2015-05-21 20:12
This really looks weird. On my server, if I set access deny to a certain user at the folder level:

![51-1](https://cloud.githubusercontent.com/assets/7997931/7757871/4d061e98-ffba-11e4-9bd6-7fcf1ad9d505.png)

When the user logon, he could not see any commands in that folder:

![51-2](https://cloud.githubusercontent.com/assets/7997931/7757885/687386e8-ffba-11e4-9ce6-23568b81744b.png)

If I set the access control on a specific file:

![51-3](https://cloud.githubusercontent.com/assets/7997931/7757888/7ab5d46e-ffba-11e4-89a0-6dc6759ea805.png)

The user could run it but will fail with an access error:

![51-4](https://cloud.githubusercontent.com/assets/7997931/7757892/8b4a5a2a-ffba-11e4-9879-8823e0c32fcc.png)

There isn't any other special configuration on my IIS besides Windows Authentication. 

I suggest you to install a new Windows 2012 R2 server with all default configuration and then setup webcommander there.

**Comment by aschi75** [comment] 2015-05-22 11:52
I setup a new 2012 R2 Server and everything worked as expected, Thank you very much.

**Comment by 9whirls** [comment] 2015-05-23 14:17
Cool. Glad to know you got the issue solved.
I will close it.
Let me know when you need further assistance.

**Closed by 9whirls** 2015-05-23 14:17 UTC
Labels: question

**Comment by aschi75** [comment] 2015-05-26 11:25
Hi, I answered to quickly. 
As I said I'm able to restrict the view to the scripts to specific Users with ntfs Permissions.
But I'm not able anymore to execute them successfully, they start but finish with no result. I guess that's because I forgot to set the Physical Path Credentials in IIS as administrator (explained in the installation manual). As soon as i set these Permission I'm able to execute the script but all scripts are viewable again for all users.
Did you also set the physical path Credentials to a Administrator Account?

**Comment by 9whirls** [comment] 2015-05-26 13:52
Nope, I use the default setting which is called pass-through.

**Comment by aschi75** [comment] 2015-05-26 14:35
Ok, that makes sense. I went step by step through the "WebCommanderInstructions_v1.1.pdf".  there is written at Point 11: "Make sure to connect as administrator in the basic settings of the web site". that's also why it doesn't worked with the other installation.

Because I have to run some commands/connnections as different User I used the following in the Scripts:
$encrypted = "01000000d08c9ddf0115d......"
$pw = ConvertTo-SecureString -string $encrypted 
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist $user,$pw
connect-qadService -service "servername:389" -Credential $cred 

the Advantage is that I don't have to store the password in cleartext. But because the encrypted password with convertfrom-securestring has to be made with the user which is running the script and this is not "Administrator" anymore, this doesn't work anymore.
The Source Code of the Script is viewable with webcommander and I dont' want the password as cleartext in the Script. The User itself don't know the Credentials and don't have Permissions. I can't use Parameters to ask for the credentials. there must be an impersonation in the script.
Is there another possibility with webcommander?

**Comment by 9whirls** [comment] 2015-05-26 14:46
Ok, I will get back to you later in a couple of days. I am currently on a tour. Sorry.

**Comment by 9whirls** [comment] 2015-05-28 14:04
sorry, I don't understand why the convert from or to cmdlet doesn't work when the user is not administrator. if the script couldn't run by the non-admin user in powershell console, it couldn't run in webcommander either.
you could disable the show source code feature by deleting the php file in www folder.

**Comment by aschi75** [comment] 2015-05-29 07:41
As in this article described:
http://powershell.org/wp/2013/11/24/saving-passwords-and-preventing-other-processes-from-decrypting-them/
If you encrypt a Password -> only the same user account (and on the same computer) is able to decrypt the protected data

But I just found another article where you can encrypt/decrypt with an additional Key where the user and computer doesn’t matter.
http://www.adminarsenal.com/admin-arsenal-blog/secure-password-with-powershell-encrypting-credentials-part-2

this Problem is solved but If I use „pass-through authentication“ I’not able to get the scripts running. Even a simple writeCustomizedMsg "test" isn’t working. I get an empty Webcommander Result Page.
I can put the user which is running the script into the administrator Group but Webcommander gives no output. It works in the powershell console on the server but not through webcommander.
It works if I set again the Local Administrator into the physical Path Credentials. But if I do this I can’t restrict the access to the scripts.
do I have to set additional Permissions somewhere?

**Comment by 9whirls** [comment] 2015-05-31 16:16
Please keep in mind, when you get an "empty result", there should be some error message in the source code of the web page. 

So you encrypt a password as administrator. When other users run the script with their own crendentials, they could decrypt the secure string from poweshell console but couldn't do so from webcommander. Is my understanding correct? If this is the case, I don't think this problem could be solved from webcommander. 

My suggestion is to remove the usage of the secure string in your script. You already authenticate users from IIS, what's the purpose of the other password?

**Comment by aschi75** [comment] 2015-06-01 08:24
Because the user doesn't have Permissions to some Resources I have to make impersonation. My goal is also not to store passwords in cleartext in scripts.
for testing purpose I removed securestring and stored the password in cleartext:

I still get an empty Webcommander Page. There's no error message in the Source. I even get the correct result in the Source Code. I was never able to run any Script successful if I set the Website to "pass trough authentication". It works if I use the Administrator Account in the "physical path credentials". This happens also with a script where the only command is writeCustomizedMsg "test". it also works if I add the user which is executing the script into the administrator group on the server. But we "never" add domain user to the administrator Group on our Server. Does all users need Administrative Permissions on the Server? that would be a noGo in our company.
 
Not sure If we have a Group Policy set which is responsible for all this troubles but I just don't get it working as I think it should.

**Comment by 9whirls** [comment] 2015-06-01 15:05
Do you mean the probkem has nothing to do with secure string or password?
Your latest comment sounds the real problem is the pass-through setting on IIS. When you set that, no script could run, correct?

**Comment by aschi75** [comment] 2015-06-01 15:09
yes, that is correct. I didn't test the scripts after setting the pass through authentication because everything looked good. It took some time until I fount out that it depends on this and not on the secure password.

**Comment by 9whirls** [comment] 2015-06-01 15:26
I couldn't reproduce the problem on my server. Pass-through works for both admin and non-admin users here.
Did you ever try logon webcommander server as a non-admin user and run script from powershell console? If you have a policy preventing non-admin user from doing so, this should fail too.

**Comment by aschi75** [comment] 2015-06-02 06:45
I added the user to the remote desktop User group and logged into the webcommander Server. The Script is working in the powershell console.

**Comment by 9whirls** [comment] 2015-06-02 07:19
ok, so this is not a policy issue either.
I have no idea why pass-through has problem on your server. I could only do some guess job now. Did you see history files (xml) created in www\history folder? 
If not, please give all users the right to write in that folder. Let's see if that helps.

**Comment by aschi75** [comment] 2015-06-02 09:26
the history logs are generated and contain the correct results. I'm also able to list the history logs but when I try to open these I get the empty result page again. Very strange behaviour. The Source Code of the Page contains the correct result as well as the history xml files. I'll setup another W2012 R2 Server and test before I join the server into our Domain. But I'm not sure if I find time this week. I'll keep you updated.

**Comment by aschi75** [comment] 2015-06-15 11:30
I installed a new System. the Server is NOTjoined to our Domain. The test script should just output "TEST". But again, if I don't specify  Physical Path Credentials the Result Page is empty, Event if I put the local User into the Administrator Group. The Script works if I start it localy in Powershell.
The Source Code of the page looks like this (part of):
Successfull, if the Administrator is set in the Path Credentials:
  <result>
    <customizedOutput>[2015-06-15 13:10:43] TEST</customizedOutput>
  </result>

empty, with pass through Authentication:
  <result>TEST
</result>

There's no  <customizedOutput>, that must be the reason why the Result Page (Code 4488) is empty.
I have no idea why it isn't working in my Environment. I'll keep the Administrator Account in the Physical path Credential and look for another Solution so restrict Access to Scripts in Webcommander for different User

**Comment by aschi75** [comment] 2015-06-15 11:33
sorry, didn't realize that html content is not diplayed correctly.
there's a flag "customizedOutput" in the successfull version which is missing in the empty Page.

**Comment by aschi75** [comment] 2015-06-15 12:08
Part of the Page Source Code as a Picture:
![wc](https://cloud.githubusercontent.com/assets/12539205/8159531/eb4071c4-1367-11e5-8e83-47029851e7c9.PNG)

**Comment by 9whirls** [comment] 2015-06-15 21:12
Sorry Roger. I'm kind of lost after reading your recent comments.
Do you still have the authentication issue? If so, please schedule a webex session so that we can debug the problem together.

**Comment by 9whirls** [comment] 2015-06-16 20:09
Hi Roger,
When you hit the blank result issue, right click the page and select view source.
If you find error message as below

gwmi : Access denied
At C:\WebCommander\powershell\objects.ps1:45 char:22
+ while ($currentId = (gwmi win32_process -Filter "processid='$currentId'").parent ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand

Please comment out line 45 to 50 in objects.ps1 and add the following line there
$runFromWeb = $true 

Let me know if this solves your problem.

**Comment by aschi75** [comment] 2015-06-17 05:29
it works with this change, even if the computer is joined in our domain.
Can I leave it this way?
Another Issue is that the execution Time is very long. the Test Script with a simple "Test" Output takes over 2 minutes. That's probably because powershell tries to connect to the Internet during startup. Because of needed proxy Settings this is not possible and it runs probably into a timeout. I didn't found a solution for that, do you have any idea how to solve this?

**Comment by 9whirls** [comment] 2015-06-17 16:41
Ok, so the problem is common user doesn't have enough privilege to get the parent process of the powershell script. I've updated webcmd.php and objects.ps1 to use another way to tell if the script is triggered by webcommander.
You could either keep your current code or pull the latest code from github.

It would be a better practice to trace a single issue in this thread. Please open a new one for the long execution time thing. 
When you do so, please post your test script and how long it takes to run the script from powershell console.

**Comment by aschi75** [comment] 2015-06-18 06:46
I downloaded both Files and it works now, Thanks for your Help. I'll Open a new thread for the long execution time.
